article/urls.py
from django.urls import path
from .views import article_detail_view,add_article_view


app_name='article'

urlpatterns=[
    path('detail/<id>',article_detail_view, name='article_detail'),
    path('add_article',add_article_view, name='add_article'),
]

btilms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userauth.urls')),
    path('note/',include('note.urls')),
    path('notice/',include('notice.urls')),
    path('course/',include('course.urls')),
    path('article/',include('article.urls')),
    path('routine/',include('routine.urls')),
    path('summernote/', include('django_summernote.urls')),
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns +=static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)



admin.site.site_title = "BTI-LMS Admistration"
admin.site.site_header = "BTI-LMS Admistration"
admin.site.index_title = "BTI-LMS Admistration"

course/urls.py
from django.urls import path
from .views import course_view, course_detail_view


app_name='course'

urlpatterns=[
    path('',course_view, name='course'),
    path('detail/<int:id>',course_detail_view, name='detail'),


]

note/urls.py
from django.urls import path
from .views import addnote_view,usernote_view, updatenote_view, delete_note


app_name='note'

urlpatterns=[
    path('addnote/',addnote_view, name='addnote'),
    path('allnote/',usernote_view, name='allnote'),
    path('update/<id>',updatenote_view, name='update'),
    path('delete/<id>',delete_note, name='delete_note')
]

course/models.py
from django.db import models
from userauth.models import Batch
from django.contrib.auth.models import User


class Course(models.Model):
    name = models.CharField(max_length=200)
    batch = models.ManyToManyField(Batch)
    teacher = models.ManyToManyField(User)
    pic = models.ImageField(null=False, upload_to='coursepics')
    cr_hours = models.IntegerField(default=0)
    desc = models.TextField(null=True)

    def __str__(self):
        return self.name

course/views.py
from django.shortcuts import render, get_object_or_404
from .models import Course
from userauth.models import UserDetail, Batch
from note.models import Note
from article.models import Article

def course_view(request):
    user = request.user
    acuser = UserDetail.objects.get(user=user)
    courses = Course.objects.filter(batch=acuser.batch)
    print(courses)
    return render(request,'course/course.html',{'courses':courses})

def course_detail_view(request,id):
    course = get_object_or_404(Course,id=id)
    notes = Note.objects.filter(course=course)
    articles = Article.objects.filter(course=course).order_by('-id')


    context={
        'course':course,
        'notes':notes,
        'articles':articles
    }
    return render(request, 'course/detail.html', context)

templates/course/course.html
{%extends 'base.html'%}
{%block title%} Course {%endblock%}

{%block body%}

<style>
    .course:hover{
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    color: blue;
    transition: 0.9s;
}
</style>
<div class="my-3 py-3 bg-white text-center shadow-sm fw-light">
    <h4>My Courses & Learning Plans</h4>
</div>

<div class="my-2 container">
    <div class="row p-0">
        {% for i in courses %}
        <div class="col-lg-3 col-md-4 col-6   p-2  mb-3" >
            <div class="bg-white border course"  >
            <a  href="{% url 'course:detail' id=i.id %}" class="text-decoration-none text-dark  ">
               
                    <img src="{{i.pic.url}}" class="img-fluid" alt="coursepic">

                <span class="badge bg-danger mx-3 mt-2 ">{{i.cr_hours}} credits</span>
            <div class="p-3">
                <h6 class="">{{i.name}}</h6>
                <small title="{{i.desc}}" style="font-size: 12px;" >{{i.desc|truncatechars:65}}</small>
                 
            </div>
        </a>
    </div>

        </div>
        {%empty%}
        <p class="text-center p-5 m-5">No Courses found.</p>
        {%endfor%}
    </div>
</div>

{%endblock%}

templates/course/detail.html
{%extends 'base.html'%}
{%block title%} Course {%endblock%}

{%block body%}


<div class="my-3 py-3 bg-white text-center shadow-sm fw-light">
    <h4>{{course.name}}</h4>
</div>
<div class="row">
    <div class="col-lg-8 my-3 mx-2  bg-white p-3">
        <h5 class="my-3">All Notes</h5> <hr>
    
        {% for i in notes%}
        <div class="mb-2 d-flex justify-content-between">
            <a href="{{i.file.url}}" download="{{i.file.url}}">{{i.name}}</a>
            <p><small>uploaded by</small>: {{i.uploader.userdetail.first_name}} {{i.uploader.userdetail.last_name}}</p>
            <p><small>uploaded time</small>: {{i.date}}</p>
    
        </div>
        <hr>
        {%empty%}
        <p class="text-center p-5 m-5">No notes available.</p>
        {%endfor%}
    </div>
    <div class="col  my-3 bg-white p-3">
        <h5 class="my-3">Associated Articles</h5> <hr>
    
        {% for i in articles%}
        <a href="{% url 'article:article_detail' id=i.id %}" class="text-decoration-none text-dark">
            <div class="mb-2 d-flex justify-content-between">
                <div><img src="{{i.img.url}}" alt="image" height="100"></div>
                <div class="ms-2 ">
                    <h5>{{i.title}}</h5>
                    <small><span>Published by: <strong>{{i.author.userdetail.first_name}} {{i.author.userdetail.last_name}}</strong></span></small><br>
                    <small><span><i>Date: <strong>{{i.date}}</strong></i></span></small>
                </div>
               
        
            </div>
        </a>
        <hr>
        {%empty%}
        <p class="text-center p-5 m-5">No articles published.</p>
        {%endfor%}
    </div>
</div>




{%endblock%}