btilms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userauth.urls')),
    path('note/',include('note.urls')),
    path('notice/',include('notice.urls')),
    path('course/',include('course.urls')),
    path('article/',include('article.urls')),
    path('routine/',include('routine.urls')),
    path('summernote/', include('django_summernote.urls')),
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns +=static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)



admin.site.site_title = "BTI-LMS Admistration"
admin.site.site_header = "BTI-LMS Admistration"
admin.site.index_title = "BTI-LMS Admistration"

note/urls.py
from django.urls import path
from .views import addnote_view,usernote_view, updatenote_view, delete_note


app_name='note'

urlpatterns=[
    path('addnote/',addnote_view, name='addnote'),
    path('allnote/',usernote_view, name='allnote'),
    path('update/<id>',updatenote_view, name='update'),
    path('delete/<id>',delete_note, name='delete_note')
]

note/models.py
from django.db import models
from course.models import Course
from django.contrib.auth.models import User

class Note(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    file = models.FileField(upload_to='notefiles')
    date = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

note/forms.py
# import form class from django
from django import forms
from .models import Note
from course.models import Course

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['course','name','file']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Get the user from kwargs
        super(NoteForm, self).__init__(*args, **kwargs)
        
        if user:
            self.fields['course'].queryset = Course.objects.filter(teacher=user)

note/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from .forms import NoteForm
from django.contrib import messages
from .models import Note


def addnote_view(request):
    form = NoteForm(user=request.user)
    if request.method == "POST":
        form = NoteForm(request.POST, request.FILES, user=request.user )
        if form.is_valid():
            fm = form.save(commit=False)
            fm.uploader = request.user
            form.save()
            messages.success(request, 'Note successfully added.')
        else:
            messages.error(request, 'Something went wrong.')
    context = {
        'form':form
    }
    return render(request,'note/addnote.html', context)




def usernote_view(request):
    user =request.user
    notes = Note.objects.filter(uploader=user)
    return render(request,'note/usernote.html',{'notes':notes})

def updatenote_view(request,id):
    note =Note.objects.get(id=id)
    form = NoteForm(user=request.user, instance=note)
    if request.method == "POST":
        form = NoteForm(request.POST, request.FILES, user=request.user, instance=note)
        if form.is_valid():
            fm = form.save(commit=False)
            fm.uploader = request.user
            if not form.cleaned_data.get('file'):
                fm.file = note.file
            form.save()
            messages.success(request, 'Note successfully updated.')
        else:
            messages.error(request, 'Something went wrong.')

    context = {
        'form':form
    }
    return render(request,'note/updatenote.html', context)


def delete_note(request, id):
    # Retrieve the note object using get_object_or_404
    note = get_object_or_404(Note, id=id)
    user= request.user
    if note.uploader == user:
        note.delete()  # Delete the note object
        messages.success(request, 'Note successfully removed.')

        return redirect('note:allnote')  # Redirect to the list of notes or any other desired URL
    
    return HttpResponse('403 Not Authorized.')

templates/note/addnote.html
{%extends 'base.html'%}
{% load bootstrap5 %}
{%block title%} Note {%endblock%}

{%block body%}
<div class="my-3 py-4 bg-white text-center shadow-sm fw-light">
    <h4>Add Notes</h4>
</div>

<div class="bg-white shadow-sm p-4">
    <form action="" method="post" enctype="multipart/form-data">

        {%csrf_token%}
        {% bootstrap_form form %}
<hr>
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn  btn-primary"> Save Note</button>

    </div>
    </form>

</div>
{%endblock%}

templates/note/allnote.html
{%extends 'base.html'%}
{%block title%} Note {%endblock%}

{%block body%}
<h1>All Note</h1>
{%endblock%}

templates/note/note.html
{%extends 'base.html'%}
{%block title%} Note {%endblock%}

{%block body%}
<h1>Note</h1>
{%endblock%}

templates/note/updatenote.html
{%extends 'base.html'%}
{% load bootstrap5 %}
{%block title%} Update Note {%endblock%}

{%block body%}
<div class="my-3 py-4 bg-white text-center shadow-sm fw-light">
    <h4>Update Note</h4>
</div>

<div class="bg-white shadow-sm p-4">
    <form action="" method="post" enctype="multipart/form-data">

        {%csrf_token%}
        {% bootstrap_form form %}
<hr>
    <div class="d-flex justify-content-center">
        <button type="submit" class="btn  btn-primary"> Update Changes</button>

    </div>
    </form>

</div>
{%endblock%}

templates/note/usernote.html
{%extends 'base.html'%}
{%block title%} Note {%endblock%}

{%block body%}
<div class="my-3 py-4 bg-white text-center shadow-sm fw-light">
    <h4>Notes added by you</h4>
</div>
<div class=" my-3   bg-white p-3">
    <h5 class="my-3">All Notes</h5> <hr>

    {% for i in notes%}
    <div class="mb-2 d-flex justify-content-between">
        <a href="{{i.file.url}}" download="{{i.file.url}}">{{i.name}}</a>
        <p><small>uploaded time</small>: {{i.date}}</p>

        <div class="btn-group">
            <a onclick="return confirm('Are you sure ?')" href="{% url 'note:delete_note' id=i.id %}" class="btn btn-danger btn-sm me-2" >Delete</a>
            <a href="{% url 'note:update' id=i.id %}" class="btn btn-outline-primary btn-sm" >Update</a href="{% url 'note:update' id=i.id %}">
        </div>

    </div>
    <hr>
    {%empty%}
    <p class="text-center p-5 m-5">No notes available.</p>
    {%endfor%}
</div>
{%endblock%}