article/urls.py
from django.urls import path
from .views import article_detail_view,add_article_view


app_name='article'

urlpatterns=[
    path('detail/<id>',article_detail_view, name='article_detail'),
    path('add_article',add_article_view, name='add_article'),
]

btilms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userauth.urls')),
    path('note/',include('note.urls')),
    path('notice/',include('notice.urls')),
    path('course/',include('course.urls')),
    path('article/',include('article.urls')),
    path('routine/',include('routine.urls')),
    path('summernote/', include('django_summernote.urls')),
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns +=static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)



admin.site.site_title = "BTI-LMS Admistration"
admin.site.site_header = "BTI-LMS Admistration"
admin.site.index_title = "BTI-LMS Admistration"

course/urls.py
from django.urls import path
from .views import course_view, course_detail_view


app_name='course'

urlpatterns=[
    path('',course_view, name='course'),
    path('detail/<int:id>',course_detail_view, name='detail'),


]

note/urls.py
from django.urls import path
from .views import addnote_view,usernote_view, updatenote_view, delete_note


app_name='note'

urlpatterns=[
    path('addnote/',addnote_view, name='addnote'),
    path('allnote/',usernote_view, name='allnote'),
    path('update/<id>',updatenote_view, name='update'),
    path('delete/<id>',delete_note, name='delete_note')
]

notice/urls.py
from django.urls import path
from .views import allnotice_view


app_name='notice'

urlpatterns=[
    path('allnotice/',allnotice_view, name='allnotice')
]

routine/urls.py
from django.urls import path
from .views import routine_view


app_name='routine'

urlpatterns=[
    path('',routine_view, name='routine')
]

templates/base.html
<!doctype html>
{% load static%}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>{%block title%} {%endblock%} | LMS-BTI</title>

    {%block head%} 
            {%endblock%}
  </head>
  
  <body class="bg-light">
 

    <div class="container">
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
      <div class="cube"></div>
     <div class="cube"></div>
        <div class="col-lg-11 mx-auto">
            {%include 'navbar.html'%}
            {%include 'messages.html' %}
            {%block body%} 
            
            {%endblock%}
            {%include 'footer.html'%}
    
        </div>
    </div>

    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    <script>
      const themeToggle = document.getElementById("theme-toggle");
  const themeLink = document.getElementById("theme-link");
  
  // Function to set the theme based on the user's preference
  function setTheme(theme) {
      if (theme === "anish") {
          document.body.classList.remove("anish-mode");
          themeToggle.checked = false;
      } else {
          document.body.classList.add("anish-mode");
          themeToggle.checked = true;
      }
  }
  
  // Function to toggle the theme
  function toggleTheme() {
      const currentTheme = localStorage.getItem("theme") || "normal";
      const newTheme = currentTheme === "normal" ? "anish" : "normal";
      
      localStorage.setItem("theme", newTheme);
      setTheme(newTheme);
      if (currentTheme === "anish"){
        setTimeout(anish_message, 2000);
      }      
  }
  function anish_message(){
    alert("मिठो कलर छैन त ! 😅")
  }
  // Initialize the theme based on user's preference
  setTheme(localStorage.getItem("theme") || "normal");
  
  // Add a click event listener to the theme toggle
  themeToggle.addEventListener("click", toggleTheme);
  
  </script>
  </body>
</html>

templates/messages.html
{% if messages %}
{% for message in messages %}
    {% if message.tags == 'success'%}
   <div class="col-lg-4 mx-auto">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
   </div>
    
    {% elif message.tags == 'error'%}
   <div class="col-lg-4 mx-auto">
        
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      </div>
    {% endif %}
{% endfor %}
{% endif %}

templates/navbar.html
{% if request.user.is_authenticated%}
<!-- check if the logged in user is student or teacher -->
  {% if user.userdetail.is_student%} 
  <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'course:course' %}">BTI-LMS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'userauth:profile'%}"><svg xmlns="http://www.w3.org/2000/svg" height="0.7em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg> {{request.user.username}}</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'course:course'%}">My Courses</a>
          </li>
          <li class="nav-item">
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notice:allnotice'%}">Notices</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'routine:routine'%}">Routines</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" onclick="return confirm('Do you really want to logout?')" href="{% url 'userauth:logout'%}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" >
              {% include 'themebutton.html'%}
            </a>
          </li>
     
        </ul>
      </div>
    </div>
  </nav>
  {%else%}
  <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'userauth:profile' %}">BTI-LMS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'userauth:profile' %}"><svg xmlns="http://www.w3.org/2000/svg" height="0.7em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg> {{request.user.username}}</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          <button class="btn btn-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg></button>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 id="offcanvasRightLabel">BTI-LMS Professor Mode</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div> <hr>
  <div class="offcanvas-body">


        <li><a class="dropdown-item" href="{% url 'article:add_article'%}">Publish Article</a></li>

        <hr>
    
      
        <li><a class="dropdown-item" href="{% url 'note:allnote'%}">All Notes</a></li>
        <li><a class="dropdown-item" href="{% url 'note:addnote'%}">Add Note</a></li>
     
        <hr>
     
        <li><a class="dropdown-item" href="{% url 'notice:allnotice'%}">All Notices</a></li>
     
        <hr>

        <li><a class="dropdown-item" href="">All Routines</a></li>
        <li><a class="dropdown-item" href="">Add Routine</a></li>
      
        <hr>

    <li>
      <a class="dropdown-item text-danger" onclick="return confirm('Do you really want to logout?')" href="{% url 'userauth:logout'%}">Logout</a>
    </li>
    
  </div>
</div>
        
     
        </ul>
      </div>
    </div>
  </nav>
  {%endif%}




  {%else%}

  <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BTI-LMS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
       
          <li class="nav-item">
            <a class="nav-link" href="{% url 'userauth:login'%}">Login</a>
          </li>
         <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'userauth:howtouse'%}">How to use</a>
          </li>
     
        </ul>
      </div>
    </div>
  </nav>


  {%endif%}

templates/themebutton.html
<div class="slider-container" title="Anish Mode Toggle">
    <label class="slider">
        <input type="checkbox" id="theme-toggle">
        <span class="slider-circle"></span>
    </label>
</div>